[window]
padding = { x = 10, y = 10 }
opacity = 0.95
option_as_alt = "Both"

[font]
size = 22

[font.normal]
family = "MesloLGS NF"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[cursor]
style = { shape = "Beam", blinking = "On" }

[terminal.shell]
program = "/bin/zsh"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
